### ISSUE TITLE
 Cannot use snapshots without enabling the 'Saved Game' feature in the Play console

### ISSUE THREAD

**Issue by Clemkd** [Iakobs/godot-play-game-services#23]
Hello, I can't seem to use the "snapshots" function.
I tried on my own Android smartphone and on an emulator.

In the game console, this function is enabled:
![image](https://github.com/Iakobs/godot-play-game-services/assets/2260195/2c1dbb01-ecb4-4d26-95bf-c961501eed2a)
![image](https://github.com/Iakobs/godot-play-game-services/assets/2260195/75d0bb9a-021b-4bfb-887d-64e4e3bd9ee7)

I've also registered my gmail account as a tester.
![image](https://github.com/Iakobs/godot-play-game-services/assets/2260195/400ba427-e2dc-4af9-a6a3-3d048fbee025)

Logcat:
```
03-09 18:47:09.654  1151  1215 D SnapshotsProxy: Loading snapshot with name mysave.
03-09 18:47:09.665  1151  1151 E SnapshotsProxy: Failed to load snapshots. Cause: java.lang.IllegalStateException: Cannot use snapshots without enabling the 'Saved Game' feature in the
Play console
03-09 18:47:09.665  1151  1151 E SnapshotsProxy: java.lang.IllegalStateException: Cannot use snapshots without enabling the 'Saved Game' feature in the Play console
03-09 18:47:09.665  1151  1151 E SnapshotsProxy:        at android.os.Parcel.createExceptionOrNull(Parcel.java:3019)
03-09 18:47:09.665  1151  1151 E SnapshotsProxy:        at android.os.Parcel.createException(Parcel.java:2995)
03-09 18:47:09.665  1151  1151 E SnapshotsProxy:        at android.os.Parcel.readException(Parcel.java:2978)
03-09 18:47:09.665  1151  1151 E SnapshotsProxy:        at android.os.Parcel.readException(Parcel.java:2920)
03-09 18:47:09.665  1151  1151 E SnapshotsProxy:        at com.google.android.gms.internal.games_v2.zza.zzc(com.google.android.gms:play-services-games-v2@@19.0.0:3)
03-09 18:47:09.665  1151  1151 E SnapshotsProxy:        at com.google.android.gms.games.internal.zzap.zzH(com.google.android.gms:play-services-games-v2@@19.0.0:4)
03-09 18:47:09.665  1151  1151 E SnapshotsProxy:        at com.google.android.gms.games.internal.zzak.zzJ(com.google.android.gms:play-services-games-v2@@19.0.0:1)
03-09 18:47:09.665  1151  1151 E SnapshotsProxy:        at com.google.android.gms.internal.games_v2.zzez.accept(com.google.android.gms:play-services-games-v2@@19.0.0:1)
03-09 18:47:09.665  1151  1151 E SnapshotsProxy:        at com.google.android.gms.common.api.internal.zacv.doExecute(com.google.android.gms:play-services-base@@18.0.1:1)
03-09 18:47:09.665  1151  1151 E SnapshotsProxy:        at com.google.android.gms.common.api.internal.zag.zaf(com.google.android.gms:play-services-base@@18.0.1:1)
03-09 18:47:09.665  1151  1151 E SnapshotsProxy:        at com.google.android.gms.common.api.internal.zabq.zaJ(com.google.android.gms:play-services-base@@18.0.1:2)
03-09 18:47:09.665  1151  1151 E SnapshotsProxy:        at com.google.android.gms.common.api.internal.zabq.zaL(com.google.android.gms:play-services-base@@18.0.1:5)
03-09 18:47:09.665  1151  1151 E SnapshotsProxy:        at com.google.android.gms.common.api.internal.zabq.zap(com.google.android.gms:play-services-base@@18.0.1:3)
03-09 18:47:09.665  1151  1151 E SnapshotsProxy:        at com.google.android.gms.common.api.internal.GoogleApiManager.handleMessage(com.google.android.gms:play-services-base@@18.0.1:64)
03-09 18:47:09.665  1151  1151 E SnapshotsProxy:        at android.os.Handler.dispatchMessage(Handler.java:102)
03-09 18:47:09.665  1151  1151 E SnapshotsProxy:        at android.os.Looper.loopOnce(Looper.java:210)
03-09 18:47:09.665  1151  1151 E SnapshotsProxy:        at android.os.Looper.loop(Looper.java:299)
03-09 18:47:09.665  1151  1151 E SnapshotsProxy:        at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by Iakobs** [comment]
Hi @Clemkd thanks for your interest in the plugin! The settings in the screenshot look right, but have you published them?

You have to publish any changes made in play games services separately and before hand publishing the app itself. You can check this link from Google explaining the process: https://developer.android.com/games/pgs/console/publish

Please, let me know if this helped!

**Comment by Clemkd** [comment]
Thank you @lakobs for the quick and accurate reply!
I just published following the directions. I'll come back here after validating if it's working (~2h according to Google).

**Comment by Iakobs** [comment]
sure, no worries! Google says a couple hours, but sometimes it's immediate, in case you want to check!

**Comment by Clemkd** [comment]
Not working yet...
![image](https://github.com/Iakobs/godot-play-game-services/assets/2260195/3c46d571-c44d-4d77-8186-830d45656824)
![image](https://github.com/Iakobs/godot-play-game-services/assets/2260195/2f8fd1ca-cc0c-4fd9-90a9-7ccee98cb990)

**Comment by Clemkd** [comment]
OK, 2 personal accounts are registered as testers, only one works.

**Comment by Iakobs** [comment]
Oh ok, that's still strange though. Configuring Google is a nightmare in general, I had lots of problems too. Glad it's partially working, hope you can figure it out!
